# fly.toml app configuration file generated for docker-lavalink on 2026-03-05T10:46:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'docker-lavalink'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 2333
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[env]
  LAVALINK_SERVER_PASSWORD=domi
  PLUGINS_YOUTUBE_OAUTH_REFRESHTOKEN="1//05kuZSDVadQULCgYIARAAGAUSNwF-L9IrWQZTMsVJR1AvPCnvikA8BkHEEMZRL6ygm8-fyXAR3zO6bWlqhiz692LSrIRZdrKx-Lc"
  SERVER_PORT=2333
  COMPOSE_PROJECT_NAME=lavalink
